---
engines:
  markdownlint:
    enabled: true
  vint:
    enabled: true
  shellcheck:
    enabled: true
  bundler-audit:
    enabled: true
    config:
      path: test/Gemfile.lock
  rubocop:
    enabled: true
  foodcritic:
    enabled: true
ratings:
  paths:
  - "**.sh"
  - "**.vim"
  - "**.rb"
exclude_paths:
  - vim/.vim/colors/
  - docker/bash_completion.sh
