language: bash

sudo: true

before_install: rvm use system

install:
  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox --fix-missing
  - sudo apt-get install vagrant
  - bundle install --gemfile=test/Gemfile
  - bash test/install.sh

script:
  - sh test/verify.sh
  - rake --rakefile=test/Rakefile
