language: bash

sudo: true
cache: bundler

install:
  # virtualbox
  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox --fix-missing
  - sudo apt-get install linux-generic linux-image-generic linux-headers-generic linux-signed-generic
  - sudo apt-get install virtualbox-ose-dkms
  - sudo dpkg-reconfigure virtualbox-dkms
  - sudo dpkg-reconfigure virtualbox

  # vagrant
  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb

  # shellcheck
  - sudo wget http://ftp.debian.org/debian/pool/main/s/shellcheck/shellcheck_0.3.7-1_amd64.deb
  - sudo dpkg -i shellcheck_0.3.7-1_amd64.deb

  - bundle install --gemfile=test/Gemfile

before_script: VBoxManage --version

script:
  - rake --rakefile=test/Rakefile
