language: bash

sudo: true

install:
  - sudo apt-get update -q
  - sudo apt-get install virtualbox-ose-dkms
  - sudo apt-get install -q virtualbox --fix-missing
  - sudo dpkg-reconfigure virtualbox-dkms
  - sudo dpkg-reconfigure virtualbox

  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb

  - bundle install --gemfile=test/Gemfile
  - bash test/install.sh

before_script: VBoxManage --version

script:
  - sh test/verify.sh
  - rake --rakefile=test/Rakefile
