language: bash
services: docker

sudo: true
cache: bundler

install:
  # shellcheck
  - sudo wget http://ftp.debian.org/debian/pool/main/s/shellcheck/shellcheck_0.3.7-1_amd64.deb
  - sudo dpkg -i shellcheck_0.3.7-1_amd64.deb

  - bundle install --gemfile=test/Gemfile --without vagrant

script:
  - bash test/verify.sh
  - KITCHEN_LOCAL_YAML="./.kitchen.docker.yml" rake --rakefile=test/Rakefile test:integration
