language: bash

sudo: true

install:
  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox --fix-missing
  - sudo apt-get install vagrant shellcheck
  - bundle install --gemfile=test/Gemfile

script:
  - sh test/verify.sh
