language: ruby
services: docker

sudo: true
cache:
    directories:
        - $HOME/test/vendor/bundle
rvm: 2.2

install:
  # shellcheck
  - sudo wget http://ftp.debian.org/debian/pool/main/s/shellcheck/shellcheck_0.3.7-5_amd64.deb
  - sudo dpkg -i shellcheck_0.3.7-5_amd64.deb

  - travis_wait bundle install --gemfile=test/Gemfile --without vagrant

script:
  - bash test/verify.sh
  - KITCHEN_LOCAL_YAML="./.kitchen.docker.yml" rake --rakefile=test/Rakefile test:integration
